version: '3.8'

services:
  # ASP.NET Core API
  api:
    build:
      context: .
      dockerfile: src/Pictyping.API/Dockerfile.simple
    ports:
      - "0.0.0.0:5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Database=pictyping;Username=postgres;Password=password
      - ConnectionStrings__Redis=redis:6379
      - Jwt__Key=ThisIsMySecretKeyForJWTTokenGeneration2024!
      - Jwt__Issuer=PictypingAPI
      - Jwt__Audience=PictypingWebApp
      - Jwt__ExpiryMinutes=60
      - Authentication__Google__ClientId=your_google_client_id
      - Authentication__Google__ClientSecret=your_google_client_secret
    depends_on:
      - db
      - redis
    # volumes:
    #   - ./src/Pictyping.API:/app
    networks:
      - pictyping-network

  # React フロントエンド
  web:
    build:
      context: .
      dockerfile: src/Pictyping.Web/Dockerfile
      target: development
    ports:
      - "0.0.0.0:3000:3000"
    environment:
      - VITE_API_URL=http://api:5000
    depends_on:
      - api
    volumes:
      - ./src/Pictyping.Web:/app
      - /app/node_modules
    networks:
      - pictyping-network

  # PostgreSQL (既存のデータベースを使用)
  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=pictyping
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "0.0.0.0:5432:5432"
    networks:
      - pictyping-network

  # Redis (既存のインスタンスと同じ設定)
  redis:
    image: redis:latest
    restart: always
    ports:
      - "0.0.0.0:6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - pictyping-network

  # Nginx (リバースプロキシ)
  nginx:
    image: nginx:alpine
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - api
      - web
    networks:
      - pictyping-network

networks:
  pictyping-network:
    driver: bridge

volumes:
  postgres_data:
  redis_data: