/*
 * Pictyping API
 *
 * Pictyping game API for typing battles and rankings
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = Pictyping.UnityClient.Client.OpenAPIDateConverter;

namespace Pictyping.UnityClient.Model
{
    /// <summary>
    /// ExchangeCodeRequest
    /// </summary>
    [DataContract(Name = "ExchangeCodeRequest")]
    public partial class ExchangeCodeRequest
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ExchangeCodeRequest" /> class.
        /// </summary>
        /// <param name="code">code.</param>
        public ExchangeCodeRequest(string code = default)
        {
            this.Code = code;
        }

        /// <summary>
        /// Gets or Sets Code
        /// </summary>
        [DataMember(Name = "code", EmitDefaultValue = false)]
        public string Code { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ExchangeCodeRequest {\n");
            sb.Append("  Code: ").Append(Code).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
