/*
 * Pictyping API
 *
 * Pictyping game API for typing battles and rankings
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = Pictyping.UnityClient.Client.OpenAPIDateConverter;

namespace Pictyping.UnityClient.Model
{
    /// <summary>
    /// UpdateRatingRequest
    /// </summary>
    [DataContract(Name = "UpdateRatingRequest")]
    public partial class UpdateRatingRequest
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="UpdateRatingRequest" /> class.
        /// </summary>
        /// <param name="newRating">newRating.</param>
        public UpdateRatingRequest(int newRating = default)
        {
            this.NewRating = newRating;
        }

        /// <summary>
        /// Gets or Sets NewRating
        /// </summary>
        [DataMember(Name = "newRating", EmitDefaultValue = false)]
        public int NewRating { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class UpdateRatingRequest {\n");
            sb.Append("  NewRating: ").Append(NewRating).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
